cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'bash-completion'
brew 'git'
brew 'openssl'
brew 'python'
brew 'speedtest-cli'
brew 'unrar'
brew 'wget'

cask '1password'
cask 'aerial'
cask 'alfred'
cask 'bartender'
cask 'battle-net'
cask 'cleanmymac'
cask 'discord'
cask 'fantastical'
cask 'firefox'
cask 'istat-menus'
cask 'iterm2'
cask 'little-snitch'
cask 'logi-options+'
cask 'logitech-g-hub'
cask 'messenger'
cask 'microsoft-office'
cask 'nextcloud'
cask 'plex'
cask 'protonvpn'
cask 'raspberry-pi-imager'
cask 'spotify'
cask 'steam'
cask 'tailscale' 
cask 'teamviewer'
cask 'termius'
cask 'transmit'
cask 'visual-studio-code'
cask 'vivaldi'
cask 'vlc'
